// {Name: Alan_Safety_1_Data}
// {Description: Alan Safety Data}
// {Visibility: Admin}

project.NATURE_CODES = {
    "ABAN" : ["abandoned vehicle"],
    "ABCV" : [],
    "ABDU" : ["abduction"],
    "ABDU3" : ["abduction low priority"],
    "ABPN" : ["abdominal pain"],
    "AC-E" : [],
    "AC50" : ["accident over 50 miles per hour"],
    "ACAC" : ["accident aircraft"],
    "ACBT" : ["accident boat"],
    "ACCP" : ["accident city property"],
    "ACCP2" : ["accident city property normal"],
    "ACEX" : ["accident extrication"],
    "ACFD" : ["accident fire department"],
    "ACHR" : ["accident hit and run"],
    "ACHR2" : ["accident hit and run normal"],
    "ACHR3" : ["accident hit run priority 3"],
    "ACIN" : ["accident industrial"],
    "ACLS" : ["advanced care life support"],
    "ACMC" : ["motorcycle accident"],
    "ACPC" : ["police car accident"],
    "ACPD" : ["accident property damage"],
    "ACPD3" : ["accident property damage low"],
    "ACPDF" : ["traffic accident fire needed"],
    "ACPI" : ["accident personal injury"],
    "AHPD" : ["assist hampton police department"],
    "AI64" : ["interstate accident"],
    "AIEX" : ["interstate extrication"],
    "AINSP" : ["animal inspections"],
    "ALAR" : ["electronic alarm"],
    "ALBG" : ["burglar alarm"],
    "ALBU" : [],
    "ALGS" : ["gunshot alarm activation"],
    "ALHU" : ["hold up alarm"],
    "ALMD" : [],
    "ALPA" : [],
    "ALRC" : [],
    "ALRX" : ["allergic reaction"],
    "ALUS" : ["unspecified alarm"],
    "ANAB" : ["abandoned animal"],
    "ANBK" : ["barking animal complaint"],
    "ANBT" : ["animal bite"],
    "ANBT3" : ["animal bite 3"],
    "ANCR" : ["animal cruelty"],
    "ANDE" : ["dead animal"],
    "ANDF" : ["dog fight"],
    "ANFE" : ["animal problem feline"],
    "ANFN" : ["feline cat nuisance"],
    "ANFS" : ["feline cat stray"],
    "ANIN" : ["injured animal"],
    "ANPR" : ["animal problem"],
    "ANST" : ["stray animal"],
    "ANTP" : ["animal trapped"],
    "ANVI" : ["vicious animal"],
    "APED" : ["pedestrian accident"],
    "APED3" : ["pedestrian accident low priority"],
    "ARMP" : ["armed person"],
    "ARSN" : ["arson in progress"],
    "ARSN2" : ["arson normal priority"],
    "ARSN3" : ["arson report"],
    "ARST" : ["cardiac respiratory arrest"],
    "ASLT" : ["assault"],
    "ASLT2" : ["assault normal"],
    "ASLT3" : ["assault low priority"],
    "ASRP" : ["assault rape"],
    "ASTF" : ["assist fire"],
    "ATUN" : ["accident bridge tunnel"],
    "BCOM" : ["burning complaint"],
    "BGDN" : ["building collapse"],
    "BKPN" : ["back pain"],
    "BLED" : ["bleeding"],
    "BOAT" : ["boat in distress"],
    "BOLO" : ["be on the look out"],
    "BOMB" : ["bomb threat"],
    "BOMB3" : ["bomb threat low priority"],
    "BPCK" : ["blood pressure check"],
    "BREA" : ["breathing problems"],
    "BTDS" : [],
    "BULD" : ["open unsecure building"],
    "BULD2" : ["open unsecure building normal"],
    "BULD3" : ["open unsecure building low priority"],
    "BURG" : ["burglary"],
    "BURG2" : ["burglary normal priority"],
    "BURG3" : ["burglary low priority"],
    "BURN" : ["burns explosion"],
    "CARB" : ["carbon monoxide inhalation"],
    "CAVE" : ["cave in confined space"],
    "CDBL" : [],
    "CDGR" : [],
    "CELL" : ["lost cellular phone report"],
    "CHAB" : ["child abuse"],
    "CHAB2" : ["child abuse normal priority"],
    "CHAB3" : ["child abuse low priority"],
    "CHBR" : [],
    "CHFD" : [],
    "CHLF" : ["child lost found"],
    "CHLF2" : ["child lost found normal priority"],
    "CHLF3" : ["child lost found low priority"],
    "CHNE" : ["child neglect"],
    "CHNE2" : ["child neglect normal priority"],
    "CHNE3" : ["child neglect low priority"],
    "CHOK" : ["choking"],
    "CHPN" : ["chest pain"],
    "CIVL" : ["civil dispute"],
    "CIVL3" : ["civil dispute low priority"],
    "CODE" : [],
    "CPOP" : ["community policing"],
    "CTWF" : [],
    "CURF" : ["curfew"],
    "DEPR" : ["vandalism"],
    "DEPR2" : ["vandalism normal priority"],
    "DEPR3" : ["vandalism low priority"],
    "DETH" : ["deceased person"],
    "DETH3" : ["deceased person report"],
    "DIAB" : ["diabetic problems"],
    "DISO" : ["disorderly conduct"],
    "DISO2" : ["disorderly person normal priority"],
    "DISO3" : ["disorderly person low priority"],
    "DMAS" : ["domestic assault"],
    "DMAS2" : ["domestic assault normal priority"],
    "DMAS3" : ["domestic assault low priority"],
    "DMST" : ["domestic problem"],
    "DMST2" : ["domestic problem normal"],
    "DMST3" : ["domestic problem low"],
    "DRUG" : ["drug related problem"],
    "DRWN" : ["drowning diving accidents"],
    "DRWO" : ["drowning open water"],
    "DSVH" : ["disabled vehicle"],
    "DUIA" : ["driving under influence high"],
    "DUIA2" : ["driving under influence normal"],
    "DUIA3" : ["driving under influence low"],
    "DUMP" : ["illegal dumping"],
    "E911" : ["e911 hangup trouble"],
    "ECOS" : [],
    "ELEC" : ["electrocution"],
    "ELEV" : ["elevated fall"],
    "ELVA" : ["elevator"],
    "EMBZ" : ["embezzelment"],
    "EMBZ2" : ["embezzlement normal"],
    "EMBZ3" : ["embezzlement low"],
    "ENEM" : [],
    "ESCP" : ["escapee"],
    "ESCP2" : ["escapee normal"],
    "ESCP3" : ["escapee low"],
    "ESCT" : ["escort"],
    "EVIC" : ["eviction"],
    "EVID" : ["evidence collection"],
    "EXDE" : [],
    "EXPO" : ["heat cold exposure"],
    "EXTR" : ["extrication"],
    "EYEP" : ["eye problem injury"],
    "FALL" : ["ground level fall"],
    "FALLS" : ["falls"],
    "FCOM" : ["fire complaint"],
    "FGHT" : ["fight"],
    "FGHT2" : ["fight normal priority"],
    "FGHT3" : ["fight low priority"],
    "FINS" : ["fire inspection"],
    "FINV" : ["fire investigation"],
    "FLOD" : ["flooded conditions broken pipe"],
    "FOLL" : ["followup"],
    "FOUT" : ["fire reported out"],
    "FRAU" : ["fraud"],
    "FRAU2" : ["fraud normal priority"],
    "FRAU3" : ["fraud low priority"],
    "FTUN" : ["fire bridge tunnel"],
    "FUEL" : ["fuel spill"],
    "FUGI" : ["fugitive"],
    "FUGI2" : ["fugitive normal"],
    "FUGI3" : ["fugitive low"],
    "FUYD" : ["fuel storage yard"],
    "FWAR" : ["fire warrant"],
    "GANG3" : ["gang activity"],
    "GUNS" : ["gunshot"],
    "GUNS3" : ["gun shot low priority"],
    "GYNE" : [],
    "HART" : ["heart problems"],
    "HCPK" : ["handicapped parking"],
    "HDAC" : [],
    "HDIN" : [],
    "HEAD" : ["headache"],
    "HELI" : ["helicopter landing zone"],
    "HEMR" : ["hemorrhage lacerations"],
    "HHHH" : [],
    "HZMT" : ["hazmat"],
    "ICAP" : ["report by phone"],
    "IGUN" : ["individual with a gun"],
    "IGUN2" : ["individual gun normal"],
    "IGUN3" : ["individual with gun low"],
    "IKNI2" : ["person with a knife"],
    "IKNI3" : ["person with a knife low"],
    "IKNIF" : ["person with knife"],
    "ILLN" : ["sick person"],
    "INAC" : [],
    "INFO" : ["information"],
    "INFOF" : ["information for fire"],
    "INTX" : ["intoxicated person"],
    "INTX2" : ["intoxicated person normal priority"],
    "INTX3" : ["intoxicated person low priority"],
    "IWPN" : [],
    "JUVN" : ["juvenile"],
    "JUVN2" : ["juvenile normal priority"],
    "JUVN3" : ["juvenile low priority"],
    "LAFB" : ["langley air force base"],
    "LARC" : ["larceny"],
    "LARC1" : ["larceny high priority"],
    "LARC2" : ["larceny normal priority"],
    "LARC3" : ["larceny low priority"],
    "LEVY" : [],
    "LIFT" : [],
    "LOCK" : ["lock in out"],
    "LOCM" : [],
    "LOST" : ["lost property"],
    "MALR" : ["medical alarm"],
    "MASS" : ["mass casualty"],
    "MASS1" : ["mass casualty high priority"],
    "MATE" : ["pregancy childbirth miscarriage"],
    "MEDC" : ["medical assist"],
    "MENT" : ["mental person"],
    "MENT3" : ["mental patient low priority"],
    "MESG" : ["message"],
    "MISA" : [],
    "MISJ" : [],
    "MISS" : ["missing person adult"],
    "MNDN" : ["man down"],
    "MOR" : ["matter of record"],
    "MORF" : ["matter of record fire"],
    "MOVE" : ["move transfer relocation"],
    "MSGA" : [],
    "MSGF" : ["phone message for fire"],
    "MSGP" : ["phone message for officer"],
    "MUAI" : ["mutual aid"],
    "MUAIP" : ["mutual aid police"],
    "MV61" : ["mv activation"],
    "NAUN" : ["nature unknow"],
    "NBOT" : ["boat fire"],
    "NBRU" : ["non structure brush grass wood"],
    "NGAS" : ["natural gas leak explosion"],
    "NGRA" : [],
    "NNNN" : ["unknown problem from newport news"],
    "NOTH" : ["non structure other"],
    "NTRA" : ["non structure trash dumpster"],
    "NUIS" : ["public nuisance"],
    "NUIS1" : ["nuisance high priority"],
    "NV64" : ["vehicle fire interstate"],
    "NVEH" : ["non structure vehicle cars"],
    "NWDS" : [],
    "ODOR" : ["investigation odor"],
    "OVDS" : ["overdose ingestion poisoning"],
    "PAGE" : ["paging personnel"],
    "PARK" : ["parking violation"],
    "PBAS" : [],
    "PBASF" : ["public assist fire"],
    "PBASP" : ["public assist police"],
    "PHNE" : ["phone complaint"],
    "POIS" : ["poisoning"],
    "PORT" : [],
    "POSV" : [],
    "PPWK" : [],
    "PQMA" : ["poquoson mutual aide"],
    "PREF" : [],
    "PROF" : ["complaint compliment"],
    "PROP" : ["property"],
    "PROW" : ["prowler"],
    "PROW2" : ["prowler normal"],
    "PROW3" : ["prowler low priority"],
    "PTCK" : ["keep check"],
    "PUBW" : ["stoppage"],
    "PURF" : [],
    "PURS" : ["pursuit"],
    "PURV" : [],
    "RAPE" : ["rape"],
    "RETN" : [],
    "RMOV" : [],
    "RNWY" : ["runaway"],
    "RNWY1" : ["runaway high priority"],
    "ROBA" : ["robbery alarm"],
    "ROBB" : ["robbery from business"],
    "ROBB2" : ["robbery business normal"],
    "ROBB3" : ["robbery low priority"],
    "ROBI" : ["robbery individual"],
    "ROBI2" : ["robbery individual normal"],
    "ROBI3" : ["robbery indiv low priority"],
    "SAPT" : ["structure fire apartment"],
    "SCGS" : [],
    "SCOM" : ["structure commercial"],
    "SDET" : ["install check smoke detector"],
    "SECU" : [],
    "SEIZ" : ["convulsions seizures"],
    "SGAS" : [],
    "SHEL" : ["ordinance shells"],
    "SHIP" : [],
    "SHIR" : [],
    "SHOS" : ["structure hospital"],
    "SHOT" : ["shooting"],
    "SHOT3" : ["shooting low priority"],
    "SIG1" : ["signal 1 officer firefighter down"],
    "SIG2" : ["signal 2"],
    "SINK" : ["boat sinking"],
    "SNON" : ["smoke detector checks"],
    "SNUR" : ["structure nursing home"],
    "SPIE" : ["pier marina fire"],
    "SPIL" : ["hazmat spill"],
    "SPRD" : ["speeding reckless"],
    "SRES" : ["structure resident"],
    "SRGS" : [],
    "SRHI" : ["structure high rise"],
    "SSCH" : ["structure school college jail"],
    "STAB" : ["stabbing"],
    "STAB3" : ["stabbing low priority"],
    "STBY" : ["standby"],
    "STLP" : [],
    "STLV" : ["stolen vehicle"],
    "STLV2" : ["stolen vehicle normal priority"],
    "STLV3" : ["stolen vehicle low priority"],
    "STOP" : ["vehicle stop"],
    "STRK" : ["stroke"],
    "STRL" : [],
    "SUIC" : ["suicide"],
    "SUIC3" : ["suicide low priority"],
    "SUPK" : [],
    "SUSB" : ["suspicious package bio"],
    "SUSP" : ["suspicious person"],
    "SUSP2" : ["suspicious person normal"],
    "SUSP3" : ["suspicious person low priority"],
    "SUSPT" : ["suspicious person terrorist"],
    "SUSV" : ["suspicious vehicle"],
    "SUSV3" : ["suspicious vehicle low priority"],
    "SXOF" : ["sexual offense"],
    "SXOF2" : ["sexual offense normal"],
    "SXOF3" : ["sexual offense low priority"],
    "SXRP" : ["sexual offense rape"],
    "SXRP2" : ["sexual offense rape normal"],
    "SXRP3" : ["sexual offense rape low"],
    "TACT" : [],
    "TAMP" : [],
    "TANK" : ["tanker fire"],
    "TECH" : [],
    "TEST" : ["test comp"],
    "TESTF" : ["test comp for fire"],
    "THRE" : ["threatening report"],
    "THRE2" : ["threatening normal priority"],
    "THRE3" : ["threatening low priority"],
    "THRO" : ["throwing an object"],
    "THRO3" : ["throw object low priority"],
    "TRAF" : ["traffic problem"],
    "TRAF1" : ["traffic high priority"],
    "TRAI" : ["train accident"],
    "TRAN" : ["transport"],
    "TRAP" : ["person trapped"],
    "TRDR" : [],
    "TREE" : ["tree limbs down"],
    "TREE1" : ["trees limbs down"],
    "TRES" : ["trespassing"],
    "TRES2" : ["trespassing normal priority"],
    "TRES3" : ["trespassing low priority"],
    "TRGN" : [],
    "TRIN" : ["traumatic injuries"],
    "TRPR" : [],
    "TWCK" : ["tower light check"],
    "UNCO" : ["unconcious"],
    "UNFP" : ["unknown fire problem"],
    "Unknown" : ["Unknown"],
    "UNSP" : ["unspecified"],
    "UNSP2" : ["unspecified normal priority"],
    "UNSP3" : ["unspecified low priority"],
    "UNSPT" : ["unspecified terrorist act"],
    "UNUN" : [],
    "VAEOC" : ["virginia emergency operations center"],
    "VAHO" : ["V A hospital"],
    "VDCA" : [],
    "W911" : ["wireless 911 call"],
    "W9112" : ["wireless 911 normal priority"],
    "W9113" : ["wireless 911 low priority"],
    "WARR" : ["warrant"],
    "WARR3" : ["warrant low priority"],
    "WEAP" : ["weapons law violation"],
    "WILD" : ["wildlife"],
    "WIRE" : ["wires down transformer"],
    "WIRE1" : ["wires down"],
    "WMDI" : [],
    "WRIT" : []
};

project.NATURE_CODES_NOT_FUZZY = [
    "embezzelment",
    "extrication"
];

project.deployments = {
    test: "fusionplatform_dev.fatpot.com",
    boston: "fatpotng1.greater-boston.net",
    wasilla: "ci.wasilla.ak.us"
};

project.errorMessages = {
    "not-authorized": "Cannot get data: authorization failed",
    "cannot-connect": "Cannot get data: cannot connect to server"
};

const Type = { CALL: 0, UNIT: 1};

project.enums = {
    Type
};

project.dispatchCenters = {
    "CPD"  : ["Cedar Park Dispatch"],
    "GTD"  : ["Georgetown Dispatch"],
    "RRD"  : ["Round Rock Dispatch"],
    "WCD"  : ["Williamson County Dispatch", "Will-co"],
    "WASD" : ["Wasilla Dispatch"],
    "NND"  : ["Newport News Dispatch"],
    "HAM"  : ["Hampton Dispatch"],
    "MECC" : ["Metro Emergency Communications Center", "meck"],
    "CD"   : ["Columbus Dispatch"],
    "NRECC": ["Northwest Regional Emergency Communications Center", "en-reck"],
    "KFD" : ["K F D"],
    "TPD" : ["T P D"],
    "JFD" : ["J F D"],
    "RPD" : ["R P D"]
};

project.unitNameAliases = {
    Ladder: ['weather', 'other', 'Latin', 'Mother', 'Slaughter', 'Father', 'Lotto', 'bladder']
};
